### ISSUE TITLE
Сотрудничество

### ISSUE THREAD

**Issue by Drombeys** [range36rus/X-Ray-Engine-1.6-Origin#1]
Хай! Есть ли какие либо контакты для связи?

**Comment by range-vs** [comment]
Доброго дня. Это Вы на почту писали?

**Comment by Drombeys** [comment]
Привет) Наш коллега ForserX с IX-Ray писал. Он сказал у тебя пока времени
нет. Хотели предложить вместе заняться редакторами, ибо цели у нас
сходятся, а контактов для связей не нашли

**Comment by range-vs** [comment]
Да, пообщались уже по почте. Раз так, то хорошо, контакт теперь есть.
